/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#e5e2e1',
        'on-secondary-fixed': '#001e2f',
        'primary-container': '#8083ff',
        'surface-variant': '#353534',
        'secondary-fixed': '#c9e6ff',
        'secondary-container': '#00a2e6',
        'on-secondary-container': '#00344e',
        'tertiary-fixed': '#ffdcc5',
        'outline-variant': '#464554',
        'on-tertiary': '#4f2500',
        'surface-bright': '#393939',
        'inverse-surface': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        'on-primary-fixed-variant': '#2f2ebe',
        'primary-fixed': '#e1e0ff',
        error: '#ffb4ab',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-container': '#d97721',
        outline: '#908fa0',
        'tertiary-fixed-dim': '#ffb783',
        'inverse-on-surface': '#313030',
        'secondary-fixed-dim': '#89ceff',
        'surface-container-highest': '#353534',
        'on-tertiary-fixed-variant': '#703700',
        'on-tertiary-container': '#452000',
        surface: '#131313',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#494bd6',
        'on-tertiary-fixed': '#301400',
        'on-primary-container': '#0d0096',
        'on-error': '#690005',
        'surface-tint': '#c0c1ff',
        primary: '#c0c1ff',
        'on-surface-variant': '#c7c4d7',
        background: '#131313',
        'error-container': '#93000a',
        'surface-dim': '#131313',
        'surface-container': '#201f1f',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed-variant': '#004c6e',
        secondary: '#89ceff',
        tertiary: '#ffb783',
        'on-secondary': '#00344d',
        'on-primary': '#1000a9',
        'on-primary-fixed': '#07006c',
        'primary-fixed-dim': '#c0c1ff',
        'surface-container-low': '#1c1b1b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
